name: Upload Python Package to PyPI when a Release is Created

on:
  release:
    types: [created]

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/casebased
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          make poetry-download
          sudo apt-get install libopenblas-dev
          make install
      - name: Build package
        run: |
          make build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
